### ISSUE TITLE
Port card view component from Angular Patternfly

### ISSUE THREAD

**Issue by astefanutti** [patternfly/patternfly-ng#111]

**Comment by catrobson** [comment]
Angular info status card component here:  http://www.patternfly.org/angular-patternfly/#/api/patternfly.card.component:pfInfoStatusCard

**Comment by catrobson** [comment]
Card component has been converted here and can be seen in our showcase here: https://rawgit.com/patternfly/patternfly-ng/master-dist/dist-demo/#/card.   Does this fulfill your needs @astefanutti?

**Comment by astefanutti** [comment]
@catrobson Thanks for the update. I'm looking for the equivalent of the card view component: http://www.patternfly.org/angular-patternfly/#/api/patternfly.views.component:pfCardView. Having the card component ported is a great step forward.

**Comment by catrobson** [comment]
Building out the card view component has an open issue here, so I'm going to track further movement there since it follows the open issue template that I've been working through for all missing patterns and close this issue.:
https://github.com/patternfly/patternfly-ng/issues/167
