### ISSUE TITLE
Wizard's config to hideFooter

### ISSUE THREAD

**Issue by corinnekrych** [patternfly/patternfly-ng#114]
As we have hideHeader, in some wizard we need to hideFooter (the change could be dynamic) allow full size windows for the main content.
In https://github.com/patternfly/patternfly-ng/blob/master/src/app/wizard/examples/wizard-basic-example.component.ts#L107 replace by:
```
     this.wizardConfig = {
       title: 'Wizard Title',
       sidebarStyleClass: 'example-wizard-sidebar',
       stepStyleClass: 'example-wizard-step',
      hideFooter: true
     } as WizardConfig;
 ```
to enable hideFooter option.

**Comment by dlabrecq** [comment]
This would allow the wizard to be used as a modal, but it would break the PatterfnFly wizard pattern.

Since #115 has been closed, I'll close this issue as well.
