### ISSUE TITLE
Wizard's footer should have a configurable finish button

### ISSUE THREAD

**Issue by corinnekrych** [patternfly/patternfly-ng#116]
In my wizard implementation in https://github.com/fabric8-ui/fabric8-ui/tree/master/src/app/space/wizard for the forge app generator wizard I need to have both `next` ad `finish` button at the same time. 
* Next button to progress the wizard and go next step
* Finish indicates you can end the wizard even if some optional step are left.

**Comment by dlabrecq** [comment]
Since both fabric8-ui/fabric8-ui#1874 and fabric8-ui/fabric8-ui#182 have been closed, I'll close this issue. 

As of now, the UX design does not provide a finish button. However, we can revisit this if the design for OSIO changes?
