### ISSUE TITLE
Support Angular 4.0.1

### ISSUE THREAD

**Issue by dlabrecq** [patternfly/patternfly-ng#12]
The latest version of Angular is now 4.0.1, so we plan to target that instead of Angular 2. Many of the components we plan to initially merge have already been converted to Angular 4.

As I recall, the only differences encountered upgrading components to Angular 4 was with changing template tags to ng-template. Angular 2 still worked even tho template tags were deprecated.

Are there any other potential issues keeping up with the latest version of Angular?

**Comment by klinki** [comment]
In our project we skipped 4.0 and updated directly to 4.1 :) We didn't have any problems.

This checklist is quite useful:
https://angular-update-guide.firebaseapp.com/

If you select advanced app, then it should show everything what needs to be changed for 4. But for us it was really only `ng-template`.

**Comment by dlabrecq** [comment]
We're keeping the package version at ^4.0.1 (for now) in order to be compatible with lower versions
