### ISSUE TITLE
Border Inconsistency in toolbar

### ISSUE THREAD

**Issue by SMahil** [patternfly/patternfly-ng#130]
Border is inconsistent at toolbar dropdown. 

Steps to Reproduce:

Please refer the video clip: 
https://drive.google.com/a/redhat.com/file/d/0BzAb-YONh7fscmRxb2ZXOUdXMTA/view?usp=sharing

**Comment by dlabrecq** [comment]
Same behavior found with the filter from Angular Patternfly. In this example, we're switching from an input field to a dropdown menu, which uses a button with a 1px border.
