### ISSUE TITLE
Inconsistent Caret in toolbar dropdown

### ISSUE THREAD

**Issue by SMahil** [patternfly/patternfly-ng#131]
In toolbar dropdown caret icon is incosistent

Steps to Reproduce:
Please refer the video link: https://drive.google.com/a/redhat.com/file/d/0BzAb-YONh7fsbWdiQ1BJT0lvSlk/view?usp=sharing

**Comment by dlabrecq** [comment]
This is not an issue with the toolbar, but the filter fields component. 

There are different types of filters; text, select, and typeahead. The typeahead is a new feature, which was recently contributed. The 'select' type uses a button to display its underlying menu, the 'typeahead' uses div tags. 

It's the 'filter-select' style used with the button that sets font-style to italic and its color to #8b8d8f. The 'typeahead-input-container' style could/should also set the font and color to match.
