### ISSUE TITLE
Tree list: pfng-tree-list throws template parse errors

### ISSUE THREAD

**Issue by nimishamukherjee** [patternfly/patternfly-ng#133]
Steps to reproduce the issue:
1. In package.json set "patternfly-ng": "0.10.0"
2. Do a fresh npm install
3. In the component's module file, import PatternFlyNgModule (I tried ListModule also)
4. In the component's html file, add `<pfng-tree-list> Lorm Ipsum</pfng-tree-list>`

5. Check the browser console, you get the below error:
![error](https://user-images.githubusercontent.com/1892722/30413891-63f59bd2-9910-11e7-98ad-084e40a68a81.png)

**Note**
In the same html file if I try other components, like `<pfng-toast-notification> `or `<pfng-list>`, they work.

**Comment by dlabrecq** [comment]
I was able to successfully add the tree list to my own angular-cli app. It appears to work fine, so I'm closing this issue.

Note that the tree list component is part of the ListModule, so you'll need to import that. And if you're running Planner in OSIO, both will need the same package version.
