### ISSUE TITLE
Application launcher pattern

### ISSUE THREAD

**Issue by catrobson** [patternfly/patternfly-ng#145]
Can be converted from angular-patternfly:
http://www.patternfly.org/angular-patternfly/#/api/patternfly.navigation.component:pfApplicationLauncher

http://www.patternfly.org/pattern-library/application-framework/launcher/

**Comment by akoserwal** [comment]
@catrobson: I missing bit of context here. please, can you elaborate?

**Comment by catrobson** [comment]
@akoserwal PatternFly has an application launcher pattern where in the masthead, an application launcher icon can be shown that has a flyout that allows you to launch other applications.  This is useful for enterprise applications where you might have multiple applications that work closely together, but are separate UIs.

This capability already exists in our angular-patternfly implementation (the first link above).  We'd like to migrate this angular 1 code to angular 4/5 to support this same functionality in patternfly-ng repo.

Does that help or are you looking for something else @akoserwal?

**Comment by akoserwal** [comment]
@catrobson: thank you for the clarification. I would like to work on this enhancement. I might require some initial help.

**Comment by catrobson** [comment]
@akoserwal that's great!  Thanks for offering to take this work on.  If you need some initial help, I'd suggest you join our slack channel:  https://patternfly.slack.com/ #patternfly-ng channel and you can reach out to anyone as you need help there.  Alternatively @dlabrecq might be able to help you get started if you have any particular questions you want to ask here.

**Comment by akoserwal** [comment]
@catrobson: We can close this as pr is accepted #310 or once this final cleanup #313 get merged.

**Comment by akoserwal** [comment]
@catrobson: We can close this issue.
