### ISSUE TITLE
Notification drawer pattern

### ISSUE THREAD

**Issue by catrobson** [patternfly/patternfly-ng#146]
Convert notification drawer from angular-patternfly
http://www.patternfly.org/angular-patternfly/#/api/patternfly.notification.component:pfNotificationDrawer

http://www.patternfly.org/pattern-library/communication/notification-drawer/

**Comment by akoserwal** [comment]
@catrobson: I would like to work on this pattern.

**Comment by catrobson** [comment]
@akoserwal sounds great!  Do you need anything to get started?

**Comment by akoserwal** [comment]
@catrobson: I can begin now, got some understanding with application launcher work.

**Comment by akoserwal** [comment]
@catrobson : we can close this issue.

**Comment by dlabrecq** [comment]
PR https://github.com/patternfly/patternfly-ng/pull/334 has been merged
