### ISSUE TITLE
Wizard could use mobile layout

### ISSUE THREAD

**Issue by edewit** [patternfly/patternfly-ng#150]
Patternfly has a nice [mobile layout](http://www.patternfly.org/pattern-library/communication/wizard/) for the wizard that this component could use.

**Comment by edewit** [comment]
This was introduced in v3.27.6 of patternfly

**Comment by dlabrecq** [comment]
Mobile support was added to PatternFly v3.27.1
See: https://github.com/patternfly/patternfly/releases/tag/v3.27.1

**Comment by edewit** [comment]
@dlabrecq Looks a lot better now then before:
![screenshot from 2017-10-18 08-40-37](https://user-images.githubusercontent.com/51133/31704136-4477e20c-b3e0-11e7-822f-959de64d1676.png)

But the sub step title and step overview are still missing from the top bar:
![header example](http://www.patternfly.org/pattern-library/communication/wizard/img/responsive-wizard.png)

This gives the mobile user a lot more idea about where one is in the entire process

**Comment by LHinson** [comment]
@edewit @corinnekrych Apologies for the misunderstanding, I can clarify.... So far, we have only implemented the "[simplified mobile wizard](http://www.patternfly.org/pattern-library/communication/wizard/#/design)" (scroll to the bottom of the documentation) on that design doc. The reason being, we wanted to get a quick fix for a mobile solution out quickly vs what we had previously. In the future, we want to match the robust mobile design specified in the documentation. 

Do you have an immediate need for this more robust solution? 

Related to #164 cc @dlabrecq @catrobson

**Comment by corinnekrych** [comment]
@LHinson thanks for the clarification. 
Indeed better than 3.26.+ version but displaying step 2 without context on steps progress confused me.

**Comment by LHinson** [comment]
I hear you @corinnekrych and agree. I've created a story in Jira for the dedicated PF team to look at picking this up next sprint (starting 10/24). You can follow that story/progress here: https://patternfly.atlassian.net/browse/PTNFLY-2600

**Comment by dlabrecq** [comment]
@edewit Sorry, I didn't realize PatternFly delivered a simplified version of the design on patternfly.org. However, the CSS for the mobile layout will not be implemented here, but in PatternFly core. 

The patternfly-ng wizard should pick up those Patternfly changes automatically. (Unless there are additional features to be implemented?) Feel free to reopen this issue or create a new one on PatternFly: https://github.com/patternfly/patternfly/issues?
