### ISSUE TITLE
patternfly CSS 3.27+ does not work with wizard component

### ISSUE THREAD

**Issue by corinnekrych** [patternfly/patternfly-ng#157]
See:
![screenshot 2017-10-16 09 42 01_preview](https://user-images.githubusercontent.com/1395710/31601695-04f98968-b25b-11e7-9edf-06df8e560609.png)

the substep navigation are not displayed correctly.

**Comment by dlabrecq** [comment]
If you view the patternfly-ng wizard demo, it displays correctly.
https://rawgit.com/patternfly/patternfly-ng/master-dist/dist-demo/#/wizard

If you can reproduce your issue with the patternfly-ng wizard demo, please let us know?

**Comment by jeff-phillips-18** [comment]
https://github.com/patternfly/patternfly/releases/tag/v3.27.2 updated the wizard to use flex box
https://github.com/patternfly/patternfly/releases/tag/v3.27.5 made some changes to the wizard to better handle mobile.

**Comment by corinnekrych** [comment]
@jeff-phillips-18 @dlabrecq no it doesn't display properly even with patterfly latest 3.28
https://www.dropbox.com/s/q647u3lnthp9j70/Screenshot%202017-10-16%2016.36.33.png?dl=0

**Comment by dlabrecq** [comment]
Patternfly now requires a new selector, named wizard-pf-row.

The PR to fix is here:
https://github.com/patternfly/patternfly-ng/pull/158

**Comment by dlabrecq** [comment]
Fixed in v0.13.2. You'll also need to update PatternFly to v3.28.0
