### ISSUE TITLE
Component name prefix - need to avoid patternfly ng1 collisions

### ISSUE THREAD

**Issue by dgutride** [patternfly/patternfly-ng#17]
The PatternFly team identified a potential issue with using the pf-* naming convention for patternfly-ng components.  The same issue exists for the PatternFly Web Components under development.  

We'd like to recommend using pf-ng-* for the prefix but would like to see if there are any concerns with this naming approach.

**Comment by joshuawilson** [comment]
Your suggestion of pf-ng-* was my first thought but I could also see pfng-* as that looks cleaner to me.

**Comment by dgutride** [comment]
We've adopted pfng- for the component prefix.  Moving to closed.
