### ISSUE TITLE
Move area chart into separate item in showcase from sparkline

### ISSUE THREAD

**Issue by catrobson** [patternfly/patternfly-ng#182]
We have area chart implemented as part of spark-line.  Show area chart on navigation in showcase at same level as spark-line.

**Comment by dlabrecq** [comment]
We have an area chart?

**Comment by catrobson** [comment]
My understanding from the last discussion around this was that you could change a few configurations on the spark line and its essentially an area chart.  If you think we should build a separate component for that I'm ok with that too.

**Comment by dlabrecq** [comment]
Don't recall, but I'm sure the underlying chart supports it. Looks like C3 uses a similar config, just with a different 'type' property.

Not certain if we would use the same sparkline component? May be easier to create a new component since we seem to have one for each chart type.

**Comment by catrobson** [comment]
Ok, sounds good.  I'll close this issue and create a new one for adding an area graph component.

**Comment by catrobson** [comment]
https://github.com/patternfly/patternfly-ng/issues/189 to capture area graph pattern need.
