### ISSUE TITLE
Is PatternFly-ng2 a good name for this project?

### ISSUE THREAD

**Issue by dgutride** [patternfly/patternfly-ng#2]

**Comment by AllenBW** [comment]
Ekk!  Love that it's a question, I vote it is *not* a good name. Principally, [Angular peeps say stop putting numbers on things (its not angular 2 or 4 moving forward, its simply Angular vs AngularJS - 1.x](https://angular.io/presskit.html).  Secondly, yeah, gotta reiterate my personal comfortableness with the versioning of the ng here.

Suggestions:
* patternfly-angular - would be the most appropriate, but its kinda already been taken :frowning_face: 
* patternfly-ng - :vulcan_salute:  avoids version lockin also :vulcan_salute: you could also inverse this... :thinking: 
* angular-patternfly - kinda confusing given the first suggestion but inline with other [repos](https://github.com/angular-ui/ui-router/tree/legacy)

**Comment by andresgalante** [comment]
Good question @dgutride 

I agree, we should not attach it to a version. I'd rather prefix the name with "patternfly-" than with "angular-"

**Comment by dgutride** [comment]
@AllenBW  - other options we discussed would be patternfly-ngx.  I do think it might be nice to differentiate this from angular-patternfly somehow.

**Comment by AllenBW** [comment]
@dgutride oh that works, x for allllllllllll versions :world_map:

**Comment by waldenraines** [comment]
Should we just create a branch of angular-patternfly?  That is what I see a
lot of other projects doing.

Cheers,
Walden

**Comment by lorthirk** [comment]
Looking at the Angular world it seems that the most "standard" name would be ng-patternfly.

**Comment by carlosthe19916** [comment]
I agree with @lorthirk ng-patternfly is a good name

**Comment by dgutride** [comment]
The patternfly standard has been to use patternfly- as the prefix.  Would everybody be ok with patternfly-ng (based on what I'm seeing as the recommendations)?

@carlosthe19916 @lorthirk, @allenbw, @andresgalante

**Comment by bleathem** [comment]
+1 for patternfly-ng.  Having the _patternfly-_ prefix first highlights this as a patternfly project, rather than as an angular project, ie. it's not just some angular extension, but rather fits with the family of _patternfly-*_ framework integrations.

**Comment by LHinson** [comment]
+1 re: patternfly as a prefix!

**Comment by catrobson** [comment]
+1 - patternfly as prefix makes it consistent and easier to find when looking amongst the patternfly repos

**Comment by joshuawilson** [comment]
I would recommend patternfly-ng or -ngx. I'm seeing both in use. A lot of libraries that had -ng2 have gone to -ngx. But newer ones are going either way. At this point -ngx is the way the community knows that it isn't Angular 1. For me, I like the cleaner look of -ng.

**Comment by joshuawilson** [comment]
I agree with @bleathem point about keeping patternfly first because this is a patternfly project.

**Comment by andresgalante** [comment]
`-ngx` reminds me of nginx

**Comment by joshuawilson** [comment]
that is one of the downsides to that version, yet another reason to go with -ng

**Comment by guillaumevincent** [comment]
IMO `patternfly-angular` is better: explicit, not too long, prefixed by patternfly

**Comment by dgutride** [comment]
Repo renamed to patternfly-ng - thanks all for the great input.  Closing issue...
