### ISSUE TITLE
NotificationService: httpError() throws 'Cannot read property length of undefined' Exception

### ISSUE THREAD

**Issue by philipsorst** [patternfly/patternfly-ng#209]
When using `httpError()`, the NotificationService calls the `message()` function as follows:

`this.message('danger', 'Error!', message, this.persist.httpError, null, null);`

The last parameter is the moreActions array which is called as `null`.

However the ToastNotificationComponent does the following check in `ngDoCheck()`:

```
 this._showCloseButton = (this.showClose === true)
      && (this.moreActions === undefined || this.moreActions.length === 0);
```

As showClose is enabled for httpError by default, this leads to checking moreActions for undefined (which it is not) and then try to access length on a null variable which leads to an Exception.

**Comment by dlabrecq** [comment]
Fixed by: https://github.com/patternfly/patternfly-ng/pull/211
