### ISSUE TITLE
Add support for Observables in Notification Service

### ISSUE THREAD

**Issue by seanforyou23** [patternfly/patternfly-ng#222]
Currently, there is an issue with the NotificationService where, if an app uses the `OnPush` ChangeDetectionStrategy, notifications are not immediately displayed after being added with notificationService.message().

Providing observables as a means of getting/setting notifications is one way of solving this issue.

Two separate upstream applications have found the need for observables with regard to notifications

https://github.com/fabric8-ui/fabric8-ui/blob/master/src/app/shared/notifications.service.ts
and
https://github.com/syndesisio/syndesis/blob/master/app/ui/src/app/common/ui-patternfly/notification-service.ts

So, this issue is for investigating and providing support for observables to allow for a more robust interface for interacting with notifications. This may require augmenting the existing notification service or creating a new service altogether.

**Comment by dlabrecq** [comment]
This is available now
