### ISSUE TITLE
Demo menu items hidden from view

### ISSUE THREAD

**Issue by seanforyou23** [patternfly/patternfly-ng#223]
On the [demo site](http://www.patternfly.org/patternfly-ng/) there is a styling issue where the left hand nav is cut short, hiding the Services section. This makes it difficult for users to find information related to the [NotificationService](http://www.patternfly.org/patternfly-ng/#/notificationservice).

Attached image reveals what's missing from view.

<img width="222" alt="screen shot 2017-12-06 at 8 10 41 pm" src="https://user-images.githubusercontent.com/5942899/33693717-609748f2-dac2-11e7-9652-bec0e4947da7.png">

**Comment by dlabrecq** [comment]
It might be time to introduce the vertical nav component here? (Now that we have more components to list) Unless, you have a quick fix in mind?

**Comment by seanforyou23** [comment]
I don't see a quick fix that's low touch, either way it seems like the vertical nav is the way to go. So, introducing the vertical nav has my vote.

Should I create a new issue for that or should I use this ticket as the basis for that work?

**Comment by dlabrecq** [comment]
Please stand by. I have something in the works.

**Comment by dlabrecq** [comment]
Fixed by: https://github.com/patternfly/patternfly-ng/pull/232
