### ISSUE TITLE
Add Empty State pattern to showcase

### ISSUE THREAD

**Issue by catrobson** [patternfly/patternfly-ng#246]
Empty state pattern should be added to patternfly-ng that follows specifications of patternfly.org:  http://www.patternfly.org/pattern-library/communication/empty-state/#/overview

There is also an angular-patternfly implementation that can be used as a basis:
http://www.patternfly.org/angular-patternfly/#/api/patternfly.views.component:pfEmptyState

**Comment by dlabrecq** [comment]
We actually have an empty state component in patternfly-ng, ported from angular-patternfly.

**Comment by catrobson** [comment]
Awesome!  Dana mentioned this to me last week as well.  I'm hoping we can get it called out as an individual component in the showcase.  Updating the title of this issue to reflect that.

**Comment by dlabrecq** [comment]
Yes, we have an example. For some reason, it was omitted when the showcase was updated/prettified -- I'll add that back in.

**Comment by dlabrecq** [comment]
Fixed by: https://github.com/patternfly/patternfly-ng/pull/259

**Comment by catrobson** [comment]
Thanks @dlabrecq
