### ISSUE TITLE
Update ngx-bootstrap

### ISSUE THREAD

**Issue by dlabrecq** [patternfly/patternfly-ng#279]
The current ngx-bootstrap dependency is locked at 1.8.0. This is because our unit tests break with version 1.9.3. That is, anything that tests an ngx-bootstrap drop down.

We had a problem with this before and added `fixture.detectChanges()` before each test as a workaround. That forces the drop down to render. Otherwise, the drop down is not available and the test fails. Essentially, the previous workaround is no longer valid.

In order to update ngx-bootstrap to use versions '^1.8.0', we would have to fix our unit tests first.

**Comment by dlabrecq** [comment]
https://github.com/valor-software/ngx-bootstrap/issues/2188

Tried updating zone.js as suggested, but no luck. Also updated other karma and jasmine dependencies with no change.

**Comment by dlabrecq** [comment]
A couple tests appear to be missing BsDropdownConfig as a provider - this is necessary for any test that uses a drop down.

**Comment by dlabrecq** [comment]
Made some progress with the pagination test. See: https://github.com/patternfly/patternfly-ng/pull/280

**Comment by dlabrecq** [comment]
Made some progress with the following tests:

- https://github.com/patternfly/patternfly-ng/pull/288
- https://github.com/patternfly/patternfly-ng/pull/287
- https://github.com/patternfly/patternfly-ng/pull/285
- https://github.com/patternfly/patternfly-ng/pull/284
- https://github.com/patternfly/patternfly-ng/pull/283
- https://github.com/patternfly/patternfly-ng/pull/282
- https://github.com/patternfly/patternfly-ng/pull/280

**Comment by seanforyou23** [comment]
Oops, forgot to close this issue! The two PR's mentioned above resolved it.

**Comment by iamade** [comment]
please i am having this issue BsDropdownConfig as a provider  on ngx-bootstrap 6.0.1, I need help in resolving it
