### ISSUE TITLE
Documentation Framework

### ISSUE THREAD

**Issue by dgutride** [patternfly/patternfly-ng#3]
Create the framework for documenting the ng2 components (could be js/ngdoc style or some standard being adopted for ng2).

**Comment by lorthirk** [comment]
By looking around, it seems that Angular Material for Angular 2 uses JSDoc

**Comment by joshuawilson** [comment]
another one to look at is typedoc

**Comment by waldenraines** [comment]
Doesn't the AngularJS team use [dgeni](https://github.com/angular/dgeni)?  Should we consider that?

**Comment by dgutride** [comment]
We have adopted typedoc and combined that with our custom site.  It's likely style improvements are coming in the near future, we should keep typedoc when that happens as it provides solid class documentation.  Moving to closed.
