### ISSUE TITLE
Filter component example - doesn't behave properly when filtering by month

### ISSUE THREAD

**Issue by serenamarie125** [patternfly/patternfly-ng#329]
In the [PF NG example](https://rawgit.com/patternfly/patternfly-ng/master-dist/dist-demo/#/filters) filtering by month doesn't work properly.  Entering multiple months gets the user into a state which is not usable.  
<img width="928" alt="screen shot 2018-04-02 at 10 24 01 pm" src="https://user-images.githubusercontent.com/12504403/38225793-95c01230-36c4-11e8-8964-33c1f5f877c2.png">

Selecting a month after a month has already been selected should replace that filter, not be additive.  Note that the [Angular PF example](https://www.patternfly.org/angular-patternfly/#/api/patternfly.filters.component:pfFilter) works properly.

**Comment by dlabrecq** [comment]
This is just a matter of how the filter is applied in the example. This will be a simple change to replace the existing filter in the example app.
