### ISSUE TITLE
List component "simple expansion" styling issue

### ISSUE THREAD

**Issue by seanforyou23** [patternfly/patternfly-ng#333]
Notice in the [design overview for list](http://www.patternfly.org/pattern-library/content-views/list-view/#simple-expansion), the content container for the expanded list item has a border and dropshadow to distinguish it from the other page elements.

But then in the pf-ng component, there is no border or dropshadow around the expanded content container (you'll need to select the "Simple Expansion" checkbox in the [Basic/Compound Expansion list demos](http://www.patternfly.org/patternfly-ng/#/list) to see it in action.

Finally, here's an [example implementation](https://rawgit.com/patternfly/patternfly/master-dist/dist/tests/list-view-simple-expansion.html) that showcases the proper html/css used to achieve this. On the surface it looks like the issue is misalignment of the html/css.

**Comment by dlabrecq** [comment]
Not certain if the drop shadow is a more recent addition, but it's an easy fix. We simply need to apply the 'active' style when the row is expanded, like so:

`<div class="list-pf-item active"...`

**Comment by jschuler** [comment]
Fixed with:
https://github.com/patternfly/patternfly-ng/pull/370
https://github.com/patternfly/patternfly/pull/1070
