### ISSUE TITLE
Copy to clipboard component

### ISSUE THREAD

**Issue by seanforyou23** [patternfly/patternfly-ng#335]
We've found the need for a generic copy to clipboard action. This would pave the way to solve https://github.com/syndesisio/syndesis/issues/373 in a standardized manner.

Below is a screenshot to show what this functionality could look like.

![copy-clipboard](https://user-images.githubusercontent.com/5942899/38898319-a2f5ca0e-4262-11e8-83ff-7f7f1f9c87d1.png)

**Comment by dlabrecq** [comment]
We use something like this for OpenShift.io to grab the user's personal access token. Obviously, two very different designs. It would be great to be able to use this in both applications.

![screen shot 2018-04-30 at 10 06 24 am](https://user-images.githubusercontent.com/17481322/39431289-4290d9aa-4c5e-11e8-8df1-373d75eb3626.png)

**Comment by dlabrecq** [comment]
FYI @dongniwang
