### ISSUE TITLE
README.md updates

### ISSUE THREAD

**Issue by benjaminapetersen** [patternfly/patternfly-ng#35]
Would be handy to have the "Getting Started" heading caught up to make it easy to pull the repo, build & see where it is at currently.

Thanks!

**Comment by dlabrecq** [comment]
Yes. Working on porting an initial set of components. We have lots of testing to do, jsDoc to create, etc. Not quite ready for prime time.

Will make an announcement when we cut our first release.

**Comment by dgutride** [comment]
@benjaminapetersen - initial readme created (along with an alpha release at 0.0.3 - moving to closed, please try it out and let us know what you think
