### ISSUE TITLE
VerticalNavigationComponent doesn't close secondary on click

### ISSUE THREAD

**Issue by ssilvert** [patternfly/patternfly-ng#372]
The PatternFly VerticalNavigation shows that when you click an item in a secondary menu then the menu will immediately close.  I can't find a way to make this happen with the component.

**Comment by dlabrecq** [comment]
Talking with @dgutride and it sounds like the menu is expected to be dismissed after you route to a new page. Are you navigating somewhere when the menu option is clicked?

The URL defined in the vertical nav config should match a path defined in your routing module.

**Comment by dlabrecq** [comment]
If you have further questions, please join our patternfly-ng channel on [Slack](http://slack.patternfly.org/)

**Comment by ssilvert** [comment]
Hi Dan.  Didn't find you on slack.

I do navigate when the menu option is clicked.  A new page is loaded into the &lt;router-outlet&gt;.  However, the secondary navigation still does not close unless you hover or click outside the navigation and then wait a few seconds.  It should close as soon as you click the secondary option.

I think this should probably be reopened.

**Comment by dlabrecq** [comment]
I agree. The menu should be dismissed immediately.
