### ISSUE TITLE
Accessible text in toolbar needs improvement

### ISSUE THREAD

**Issue by seanforyou23** [patternfly/patternfly-ng#379]
In the toolbar demo, there is some unattractive noise brought into screen reader menus from various icons, and some important buttons like sort, and List/Table view switcher don't have accessible names at all, leaving these features difficult to use.

It would be nice to make some of this text customizable, but for now maybe we can just hide the icons to screen readers and use a sensible hard coded value for the accessible names, just so the experience isn't so confusing.

![buggy](https://user-images.githubusercontent.com/5942899/41433580-66fc6db6-6fe7-11e8-992f-2331eef0b083.jpg)

**Comment by dlabrecq** [comment]
A11y support was added via https://github.com/patternfly/patternfly-ng/commit/edbe041
