### ISSUE TITLE
Error: EEXIST: file already exists, mkdir './bundles' in some recent builds

### ISSUE THREAD

**Issue by ia3andy** [patternfly/patternfly-ng#397]
We have this error in our recent CI builds.
```
error /home/runner/launcher-frontend/node_modules/patternfly-ng: Command failed.
Exit code: 1
Command: node src/scripts/package/install.js
Arguments: 
Directory: /home/runner/launcher-frontend/node_modules/patternfly-ng
Output:
fs.js:110
    throw err;
    ^

Error: EEXIST: file already exists, mkdir './bundles'
    at Object.fs.mkdirSync (fs.js:840:3)
    at /home/runner/launcher-frontend/node_modules/patternfly-ng/src/scripts/package/install.js:85:6
    at FSReqWrap.oncomplete (fs.js:136:20)
```

We are using patternfly-ng `3.11.1`.

**Comment by dlabrecq** [comment]
What version of node/npm are you running via the CI?

I'm not seeing an issue when I install/re-install locally and our Travis CI install test also seems to be succeeding without error. Regardless, I added code to test if the directory exists before creating it. We'll have a new version available in a few minutes -- hopefully that will work for you.

**Comment by ia3andy** [comment]
We are using node `v10.3.0` with yarn `1.7.0`.

Thanks for the new version, I'll try it asap.

**Comment by dlabrecq** [comment]
I also tested with yarn, but didn't encounter any issues locally. We're building with node 8.3.0 in the Travis CI. 

Version 3.11.2 is available now.

**Comment by ia3andy** [comment]
@dlabrecq the patch fixed our bug, thanks ;)
