### ISSUE TITLE
Latest version raises `Unexpected value 'NotificationModule...'`

### ISSUE THREAD

**Issue by mprahl** [patternfly/patternfly-ng#402]
Once I started using the latest patternfly-ng, the production builds of my app (uses Angular 6) fails with the error below. There aren't any issues when running in development mode using `ng serve`, but as soon as I try to do a production build it fails.

```
ERROR in : Unexpected value 'NotificationModule in /path/to/git/node_modules/patternfly-ng/notification/notification.module.d.ts' imported by the module 'AppModule in /path/to/git/src/app/app.module.ts'. Please add a @NgModule annotation.
```

**Comment by dlabrecq** [comment]
It seems that the new clipboard-copy component broke something. Try a version before 3.12.0 while I work out what's wrong.

**Comment by dlabrecq** [comment]
It appears that the new copy service has a bad DOCUMENT injection. Unfortunately, this breaks all module imports. The only indication was a warning during the build:
```
(node:41073) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Right-hand side of 'instanceof' is not an object
(node:41073) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

In addition, I discovered that the copy component's CSS is not included correctly. The component's CSS should be included via the patternfly-ng stylesheet, not via the component's styleUrls property.

That said, I've fixed both issues and a new package will be on its way shortly. Thanks for the tip!

**Comment by dlabrecq** [comment]
FYI, version 3.12.4 is available now.

**Comment by mprahl** [comment]
@dlabrecq it's working now. Thank you!
