### ISSUE TITLE
Filter bug

### ISSUE THREAD

**Issue by LHinson** [patternfly/patternfly-ng#418]
This issue re: http://www.patternfly.org/patternfly-ng/#/filters was originally filed by @akarem on patternfly-design. See original issue here: https://github.com/patternfly/patternfly-design/issues/695

**Description of bug**

<img width="343" alt="image" src="https://user-images.githubusercontent.com/1472728/42732130-c2b37aec-8823-11e8-9552-1ebea1df4d92.png">

Here are the problems I see with this weekday filter.
First I choose Monday -> drop-down does not change it's state, but tag is appended 
<img width="421" alt="image" src="https://user-images.githubusercontent.com/1472728/42732226-3e39c5ac-8826-11e8-81de-e05b1339c07b.png">
Does it mean that I can add another weekday? It looks like yes, but If I add tuesday the tag is replaced.
<img width="414" alt="image" src="https://user-images.githubusercontent.com/1472728/42732239-6f2881bc-8826-11e8-8928-4006b5f82d8a.png">
Ok, I can't add another day. So this control acts like radio group / single-select dropdown / combobox.
What if I want to remove my selection? I click again and choose that initial option 
<img width="341" alt="image" src="https://user-images.githubusercontent.com/1472728/42732260-c23e4a30-8826-11e8-8d44-b3e543b86ed3.png">
And nothing happens..
The only way to remove selected filter is to click on `x` in "Active filters" list.

**So the question: Why this default option even there? It does nothing.**

This component looks like classic combobox with placeholder but acts like button group where first button does not have any action.

It probably should look like this (when it does not remember it's state)
```
 +------------------------------------------------------+
 |  Week Day | V | Filter by week day...            | V |
 +------------------------------------------------------+
```
or like this (when it can remember)
```
 +------------------------------------------------------+
 |  Week Day | V | No filter                        | V |
 +------------------------------------------------------+
```
while not interactive.

And like this when drop-down is activated
```
 +------------------------------------------------------+
 |  Week Day | V |                                  | V |
 +------------------------------------------------------+
                 | No filter                            |
                 | Sunday                               |
                 | Monday                               |
                 | Tuesday                              |
                 | Wednesday                            |
                 | Thursday                             |
                 | Friday                               |
                 | Saturday                             |
                 +--------------------------------------+
```
If user chooses "No filter" option, then filter should be removed. 
If user clisks on something else, then crsp filter is added/replaced.

After user chosed anything, it should look like this (when it does not remember it's state)
```
 +------------------------------------------------------+
 |  Week Day | V | Filter by week day...            | V |
 +------------------------------------------------------+
```
or like this (when it can remember)
```
 +------------------------------------------------------+
 |  Week Day | V | No filter                        | V |
 +------------------------------------------------------+
```
```
 +------------------------------------------------------+
 |  Week Day | V | Monday                           | V |
 +------------------------------------------------------+
```
If you don't want to allow user to remove filters from dropdown, then you may remove "No filter option".

_____________

So, one more time..

If it's combobox, it's legal to add default value (placeholder) as first option, but it __must__ display currently selected option and if user selects default option it __must__ be applied

If it's drop-down button group or "menu", than it __must__ __not__ display menu placeholder, it __must__ __not__ contain any buttons that don't do anything.

**Comment by dlabrecq** [comment]
Is the issue that the component's filter filed needs to show the current selection?

Other than showing the current selection (I agree that is a bug), it appears to behave similarly to the Angular Patternfly implementation, which this was ported from. http://www.patternfly.org/angular-patternfly/#/api/patternfly.filters.component:pfFilter

I'm a little confused by the terminology (i.e., what is referred to as "combox" Vs "dropdown button group" Vs "menu"). Can you please clarify what you mean by "If it's drop-down button group or menu"?

FYI, the component's filter filed currently uses either an input field or a dropdown, based on a given type; "text" or "select". (We haven't implemented any checkbox groups, yet.) While the developer implements how the filter is applied and the available filter options.

**Comment by LHinson** [comment]
@dlabrecq yeah, I think we need some design updates to clarify what happens when you can only filter on one thing vs multiple. Let me follow up on that side and we'll figure out how this impacts the implementation exactly.

**Comment by akaRem** [comment]
@dlabrecq Sorry for too many terms that I probably use a bit wrong here.

"combobox" / "dropdown list" is text field that may have only one value from provided list of options (does not have side effects, except validation, eg can't navigate, dispatch actions, mutate other components)
<img width="284" alt="image" src="https://user-images.githubusercontent.com/1472728/42809890-4dc3f64c-89bf-11e8-8fe3-4c434ab9c1da.png">
<img width="291" alt="image" src="https://user-images.githubusercontent.com/1472728/42809912-5679cbf4-89bf-11e8-8bcb-8868e1e66055.png">
(blueprintjs)
<img width="248" alt="image" src="https://user-images.githubusercontent.com/1472728/42810442-97724338-89c0-11e8-93d4-60e936a6d69b.png">
<img width="201" alt="image" src="https://user-images.githubusercontent.com/1472728/42810503-c1e375ce-89c0-11e8-8b19-1197e904c82f.png">

 (windows UI)

"dropdown button group" is a menu item, that provides drop-down list of buttons (not a text field, does not have any state, just action list)
<img width="222" alt="image" src="https://user-images.githubusercontent.com/1472728/42810043-ab1cba04-89bf-11e8-8d84-782759c0837e.png">
<img width="245" alt="image" src="https://user-images.githubusercontent.com/1472728/42810055-b26e3fa8-89bf-11e8-83e4-73fa3e75b9b9.png">
<img width="338" alt="image" src="https://user-images.githubusercontent.com/1472728/42810093-c7ae39e0-89bf-11e8-8700-e85ac7ffe9df.png">
<img width="376" alt="image" src="https://user-images.githubusercontent.com/1472728/42810100-ce7aa57e-89bf-11e8-9384-1948e4bda2b6.png">
(twitter bootstrap)
______________

PS: Take a look at these impl of the very same functionality
- http://blueprintjs.com/docs/#select/suggest
- http://blueprintjs.com/docs/#select/select-component
- http://blueprintjs.com/docs/#select/multi-select

<img width="437" alt="image" src="https://user-images.githubusercontent.com/1472728/42810219-186df366-89c0-11e8-9345-76185fab3ea3.png">
<img width="443" alt="image" src="https://user-images.githubusercontent.com/1472728/42810233-20044d64-89c0-11e8-927c-b436f0236d53.png">
<img width="573" alt="image" src="https://user-images.githubusercontent.com/1472728/42810251-29ac7b98-89c0-11e8-9043-c583c952d72d.png">
