### ISSUE TITLE
Problems with install

### ISSUE THREAD

**Issue by gperdomor** [patternfly/patternfly-ng#43]
I just installed and got this error when run `ng serve`
<img width="1148" alt="screen shot 2017-06-29 at 5 00 59 pm" src="https://user-images.githubusercontent.com/371939/27710153-aaa544b6-5cec-11e7-99ec-7f88b4aafb00.png">

**Comment by gperdomor** [comment]
This is the directory of downloaded `patternfly-ng`
<img width="299" alt="screen shot 2017-06-29 at 5 08 08 pm" src="https://user-images.githubusercontent.com/371939/27710391-926d8196-5ced-11e7-915c-18aab48e7e8e.png">

**Comment by dgutride** [comment]
@gperdomor  - there was a bug with our gh-pages build step that accidentally released the source instead of the dist files, please try again.

**Comment by gperdomor** [comment]
@dgutride `app.module.ts (11,70): Cannot find module 'patternfly-ng'.`
