### ISSUE TITLE
Update Copy Component Pattern to match PF Core

### ISSUE THREAD

**Issue by seanforyou23** [patternfly/patternfly-ng#433]
PFNG blockcopy and inlinecopy existed before it was an official pattern in patternfly core. Now that the pattern is in place on the design side, let's update our implementation to align with the styling and interactions defined at https://www.patternfly.org/pattern-library/forms-and-controls/copy-to-clipboard/

Let's minimize the breakage of public api parts and document any necessary changes.

**Comment by dlabrecq** [comment]
I don't know that we need to consolidate the two components? Other than the button style, the overall design isn't all that different. That is, it appears that there are still two types; inline and block.   And inline looks exactly the same.

Why not keep the two components, but add the style changes to the block component? That would help ensure we don't break the existing APIs.

**Comment by seanforyou23** [comment]
Yea I actually prefer keeping both just wasn't sure that was an option. I was thinking to fulfill design all the requirements needed to exist in a single component. Between the two components we have all the bases covered, so if that's ok with everyone else, it works for me!

**Comment by dlabrecq** [comment]
If we were starting from scratch, one component would do. Now that we have introduced two, we can't easily change/remove the APIs. We would be expected to deprecate one (or both) components. Then, they could be removed in a major release.

**Comment by seanforyou23** [comment]
Just an update, hitting an issue that seems to be related to the pfng demo app - interacting with input elements inside certain example components (like inlinecopy, and filter for example) causes the individual demo templates to perform a disappearing act. May require a tweak to the build, not quite sure yet. Will update again once we find the root cause.
