### ISSUE TITLE
pfng-list vertical alignment

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly-ng#436]
The image on the left of a pfng-list row should be vertically centered > 992px viewport. 

<img width="876" alt="screen shot 2018-08-02 at 4 16 00 pm" src="https://user-images.githubusercontent.com/35148959/43612521-358f2dde-9672-11e8-8c2f-2f18dea84999.png">
<img width="1008" alt="screen shot 2018-08-02 at 4 15 49 pm" src="https://user-images.githubusercontent.com/35148959/43612522-359d7380-9672-11e8-9ecd-e1fbdbf752a9.png">

For reference, here is the [list component on PF core](https://rawgit.com/patternfly/patternfly/master-dist/dist/tests/list-pf.html).

It's because of`div.pfng-list-content` in [list.component.html](https://github.com/patternfly/patternfly-ng/blob/master/src/app/list/basic-list/list.component.html) (in 2 places) that interferes with the parent classes `.list-pf-content.list-pf-content-flex`. Removing the `.pfng-list-content` element takes care of the layout issue, but looks like there are `click` and `dblclick` events added on that element that need to be resolved.

**Comment by dlabrecq** [comment]
We cannot always mimic patternfly core exactly -- core does not consider the component layouts required to work with JS frameworks.

The div container is necessary to limit where click events are supported. The `pfng-list-content` selector was added so the div's display would also support flex. However, it's possible that we could replace `pfng-list-content` with `list-pf-content list-pf-content-flex`? However, those same selectors would also be on the parent container, like so:

```
<div class="list-pf-content list-pf-content-flex">
        <div class="list-pf-content list-pf-content-flex"
             (click)="toggleSelection($event, item)"
             (dblclick)="dblClick($event, item)">
          ...
        </div>
        <!-- actions -->
        <div class="list-pf-actions">
          ...
        </div>
</div>
```

**Comment by dlabrecq** [comment]
Looking at the patternfly example, I don't see all icons being vertically aligned. Some are, but not the second example. Is that expected?

The snapshot is 1220px, but no icons are aligned when less than 992px.

![list patternfly](https://user-images.githubusercontent.com/17481322/43647890-f2428be4-9706-11e8-923f-e772871195fb.png)

**Comment by mcoker** [comment]
@dlabrecq that works for me!

re: the stacked example not being vertically aligned in the center, in the demo above where everything is center aligned, it looks like as soon as the items stack, it's aligned to the top (`flex-start`), just like the stacked example. So that looks to be by design.

**Comment by mcoker** [comment]
@dlabrecq I really appreciate you getting this in so quickly! Today's the last day of our bug fixing sprint before releasing Fuse Online 7.1, and looks like this change will make it in the release.
