### ISSUE TITLE
Typo in NotificationGroup

### ISSUE THREAD

**Issue by LarsLuz** [patternfly/patternfly-ng#451]
Hello!

I found a typo in the file "notification-group.ts" - the class name is written as "NotificaitonGroup".

Thank you for your time!

**Comment by joshuawilson** [comment]
It is not consistently misspelled either. :(

**Comment by joshuawilson** [comment]
@LarsLuz you should submit a PR to fix it.

**Comment by LarsLuz** [comment]
I hope I didn't overlook any of the typos.

**Comment by dlabrecq** [comment]
I believe this was fixed via https://github.com/patternfly/patternfly-ng/pull/452
