### ISSUE TITLE
pfng-action: can't use all bootstrap btn classes with styleClass

### ISSUE THREAD

**Issue by LarsLuz** [patternfly/patternfly-ng#458]
Hello,
I realized that it is not possible to use the bootstrap button classes (btn-danger and others) with pfng-action because btn-default is hardcoded.

Look at this line of code: https://github.com/patternfly/patternfly-ng/blob/master/src/app/action/action.component.html#L2

You usually override that class with the attribute styleClass of Action (https://github.com/patternfly/patternfly-ng/blob/master/src/app/action/action.ts). btn-primary is actually working though, that's why some examples do have blue buttons.

**Comment by dlabrecq** [comment]
The layout for the actions follow the PatternFly design. Thus, the use of the selectors btn,  btn-default, primary-action, etc. 

The stylClass attribute allows you to add your own selector. It's not meant as a replacement for the above. 

You can override by creating something more like this:

```
.btn.btn-default.primary-action: {
  &.my-selector: {
    // do something...
  }
}
```

Or, you don't have to use the actions at all. That is, you can add your own buttons directly to a list, table, etc.
