### ISSUE TITLE
can i use patternfly With angular 9?

### ISSUE THREAD

**Issue by pradosh123** [patternfly/patternfly-ng#466]
is patternfly-ng supports angular 9? (edited) 
im getting Error: Failed to compile entry-point patternfly-ng (module as esm5) due to compilation errors:
node_modules/@swimlane/ngx-datatable/release/datatable.module.d.ts:1:22 - error NG6002: Appears in the NgModule.imports of TableModule, but could not be resolved to an NgModule class.
This likely means that the library (@swimlane/ngx-datatable) which declares NgxDatatableModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.
 
while running angular 9 app

**Comment by dlabrecq** [comment]
"Patternfly-ng officially supports angular<8.0.0" -- @redallen 

"Patternfly-ng was built and tested with Angular 8 and @swimlane/ngx-datatable v13.x. If you installed @swimlane/ngx-datatable v17.x, that appears to require Angular 9?" -- @dlabrecq
