### ISSUE TITLE
Unable to install packages based on package-lock file 

### ISSUE THREAD

**Issue by soGit** [patternfly/patternfly-ng#475]
```bash
npm ERR! 404 Not Found - GET https://registry.npmjs.org/es-abstract/-/es-abstract-1.14.0.tgz
npm ERR! 404
npm ERR! 404 es-abstract@1.14.0 is not in the npm registry.
```

Seems like es-abstract unpublished v1.14.0

**Comment by dlabrecq** [comment]
Unfortunately, this project has not been supported for some time. The last commit was 5 yrs ago and it's unlikely a new version will be published.

That said, I've updated the README to indicate this project is no longer active. Will discuss archiving the repo with team owners
