### ISSUE TITLE
Contribution Guidelines

### ISSUE THREAD

**Issue by dgutride** [patternfly/patternfly-ng#5]
In Patternfly, we adhere to the Contributor Covenant Code of Conduct. We also use the Apache 2.0 license (see LICENSE.txt). We also have HTML/CSS guidelines along with an eslint.yaml which contains our JS lint standards. Our Pull Request template lives here. What sort of contribution guidelines would you like to adhere to? What lint standards would you like to see in this project? What kinds of things should we point out in our PR template for new contributions?

**Comment by joshuawilson** [comment]
Another linter is codelyzer. It has become the defacto Angular 2+ linter. The guy that wrote it helped write the Angular style guide.

**Comment by AdamJ** [comment]
I like the Contributor Covenant Code of Conduct (and I've already had interactions with the maintainers of that) and would also like to see this use a template for PR messages as well. Not sure if that fully falls under this question, but I do like having a standardized template.

**Comment by catrobson** [comment]
I also think an important part of contribution is that we ensure the contribution is a Common Pattern that should be under the PatternFly repo, not a one-off implementation that is only useful to one project

The contribution also should have some design review to make sure that it meets one of the following criteria:
- Matches the "gold standard" design specifications as designed by PatternFly
- Matches the design specifications provided for a certain project and has been made general enough to work for other projects
- Goes through a design review and matching design documentation issues are created for PatternFly

**Comment by catrobson** [comment]
Towards my first comment about ensuring the items are "Pattern-worthy", it might just be worth noting that we follow the [PatternFly general contribution guidelines](http://www.patternfly.org/get-started/contribute/), and have a few additions/alterations that are specific to the Angular-ng repo such as the design review process above.  @dgutride - should we add a contribute.md file that captures some of this information?

**Comment by waldenraines** [comment]
We should also include something about test coverage.  We could enforce this via PR automation (with something like [Coveralls](https://coveralls.io/)) but good to have in the contribution guidelines too.

**Comment by joshuawilson** [comment]
Test coverage is only an indicator and if you require a percentage then you will get it but you may have a false sense of safety. 

I think it is great to use something to show the current coverage and we should have something in the contributing doc about needed tests.

**Comment by waldenraines** [comment]
> Test coverage is only an indicator and if you require a percentage then you will get it but you may have a false sense of safety.

Preventing test padding is part of the purpose of PR reviews.  I think that enforcing a minimum percentage of coverage is a good thing because it automatically flags PRs as incomplete.  True it's only an indication of stability but it's better than no indication.

**Comment by dgutride** [comment]
That's a great idea @waldenraines for a coverage tool - if you'd like to create an issue so we can track getting it added, that would be helpful.

**Comment by waldenraines** [comment]
> That's a great idea @waldenraines for a coverage tool - if you'd like to create an issue so we can track getting it added, that would be helpful.

Sure thing - https://github.com/patternfly/patternfly-ng/issues/10

**Comment by dgutride** [comment]
Initial contribution guidelines created in the repo.  Moving to closed
