### ISSUE TITLE
Release Process

### ISSUE THREAD

**Issue by dgutride** [patternfly/patternfly-ng#6]
Today in PatternFly, we have patternfly-eng-release to manage releases. We also have some projects gravitating towards semantic-releases which automate releases to npm with semantic versioning after every PR merge based on commit message. What type of release process would you like to see used?

**Comment by joshuawilson** [comment]
I really like the semantic-release process. It is great to get fixes and updates out as soon as they are made. 

As to the "help wanted", I'd be happy to help set it up. If everyone agrees to use it.

**Comment by AllenBW** [comment]
Gonna ditto the :heart_eyes: above for semver releases, the faster fixes get to devs, the happier devs are! :taco: :dancer:

**Comment by waldenraines** [comment]
> automate releases to npm with semantic versioning after every PR merge based on commit message

Every PR?  If we merge 10 PRs in one day we'll have 10 releases?  To me that seems a little excessive.  I'm assuming that this would just update the minor version number and that a major release would require human intervention?

> I really like the semantic-release process. It is great to get fixes and updates out as soon as they are made.

They would also get bugs sooner too right?  Perhaps before they are even caught.  In this case you just end up having to update the version twice which costs the dev using the library more time than having a tested release.

I'm not necessarily opposed to this process but I am concerned that semantic releases would result in overall less stable releases than a process that groups changes together and tests them together before releasing them.  I think semantic releases could work if we were really confident and disciplined in our testing.

**Comment by dlabrecq** [comment]
Thank you for all the comments/suggestions. The semantic-release process is in place now. We've been using it successfully over the last couple weeks. 

Please reopen if issues are encountered.
