### ISSUE TITLE
Angular Component View Encapsulation

### ISSUE THREAD

**Issue by dgutride** [patternfly/patternfly-ng#7]
Angular 2+ allows for ViewEncapsulation - in order to use patternfly less, do we need to set ViewEncapsulation to none or is there a setting that lets us isolate component CSS (or should we even consider this)?

**Comment by lorthirk** [comment]
I'm not sure I understand the question... Can't we just make the components refer to both the Patternfly styles and, if needed, a per-component custom style as well?

**Comment by AdamJ** [comment]
I'd like to see this start off with ViewEncapsulation turned off (just to get it up and working with the latest Angular) and then turn it on if we find it necessary/easier. From my experience, the hardest part is when a multitude of variables and imports are used across the components.

This should be easier using the built-in LESS or PF3, but I'd like to be able to get a demo up and running soon to test out how everything builds and interacts with each other.

**Comment by dlabrecq** [comment]
+1 to turn it off. I've had difficultly overriding component styles when ViewEncapsulation is enabled. The only way I could override was using !important, which isn't good practice.

**Comment by dgutride** [comment]
Looks like this has been decided - ViewEncapsulation will be disabled on all components.
