### ISSUE TITLE
Getting 404 for basic list example HTML

### ISSUE THREAD

**Issue by gashcrumb** [patternfly/patternfly-ng#73]
Looks like this page -> https://rawgit.com/patternfly/patternfly-ng/master-dist/dist-demo/#/list

is trying to load -> https://rawgit.com/src/app/list/examples/list-basic-example.component.html

which returns a 404

**Comment by dlabrecq** [comment]
Yes, there are broken links for other components as well.

Fixed by https://github.com/patternfly/patternfly-ng/pull/75
