### ISSUE TITLE
Action Component: Use of icons with button

### ISSUE THREAD

**Issue by sjcox-rh** [patternfly/patternfly-ng#78]
Noticed that one of the buttons in the action component (add action button) is using an icon. I know in PatternFly we recommend avoiding use of icons in buttons. Should we make a note here? Also if we decide to make certain exceptions for certain buttons, there should be a rule for padding when using icons. The plus sign in the add action button is too close to the text.

<img width="393" alt="screen shot 2017-07-26 at 9 57 43 am" src="https://user-images.githubusercontent.com/16257540/28633582-24aa9890-71e9-11e7-8a10-39db9cd7cb29.png">

**Comment by dlabrecq** [comment]
In this case, we're trying to achieve feature parity with Anular Patternfly. I assume the case was made by Cloud Forms to support an icon? Will need to check with @dtaylor113, @jeff-phillips-18, and @serenamarie125.

If there is a rule for the padding, we will apply it.

**Comment by serenamarie125** [comment]
@sjcox-rh yes the PF suggestion is to avoid use of icons in buttons.  Yes @dlabrecq this is something that was initially added for CloudForms, and I think should continue to be supported.

We may want to include high level PF guidance around the fact that as a general guideline we do not recommend using icons in buttons, but possibly list the limited situations that it does make sense.  What do you think?

**Comment by dlabrecq** [comment]
Sounds good. We will add some guidance text regarding the icon, possibly at the API level.

**Comment by sjcox-rh** [comment]
Thanks @serenamarie125 for clarifying, and thanks for adding additional guidance for icons within buttons @dlabrecq

**Comment by dlabrecq** [comment]
Moved the button with icon to its own 'custom' example. Also added doc to describe that this is for testing purposes and not an official pattern.
